[package]
name = "z-gb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wayland"]
wayland = ["fltk/use-wayland"]

[dependencies]
fltk = "1.3"
